title: HackyHour Duisburg-Essen
description: Code - Tools - Science - Help - Social
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
logo: logo/HackyHour_Bildmarke.svg

gems:
  - jekyll-mentions
